In [3]:
import pandas as pd
import seaborn as sns
import numpy as np

In [4]:
data = sns.load_dataset("tips")
data

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

## Groupby

In [32]:
data.groupby("sex")

    lazy and eager evaluation

In [6]:
ls = [10,20,30,40]
ls

[10, 20, 30, 40]

In [7]:
range(1,10)

range(1, 10)

In [8]:
list(range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [24]:
import warnings
warnings.filterwarnings(action="ignore")

In [25]:
data.groupby("sex")["total_bill"].mean()

sex
Male      20.744076
Female    18.056897
Name: total_bill, dtype: float64

In [26]:
data[data["sex"] == "Male"]["total_bill"].mean()

np.float64(20.744076433121016)

In [27]:
data[data["sex"] == "Female"]["total_bill"].mean()

np.float64(18.056896551724133)

In [28]:
data.groupby("day")["total_bill"].mean()

day
Thur    17.682742
Fri     17.151579
Sat     20.441379
Sun     21.410000
Name: total_bill, dtype: float64

In [29]:
data.groupby("day")[["total_bill","tip"]].mean()

      total_bill       tip
day
Thur   17.682742  2.771452
Fri    17.151579  2.734737
Sat    20.441379  2.993103
Sun    21.410000  3.255132

In [31]:
data.groupby("sex")[["total_bill" , "tip"]].agg(["mean" , "median" , "sum"])

       total_bill                       tip
             mean median      sum      mean median     sum
sex
Male    20.744076  18.35  3256.82  3.089618   3.00  485.07
Female  18.056897  16.40  1570.95  2.833448   2.75  246.51

In [34]:
data.groupby("day")[["total_bill","tip"]].agg({
    "total_bill" : "mean" ,
    "tip" : "median"
})

      total_bill    tip
day
Thur   17.682742  2.305
Fri    17.151579  3.000
Sat    20.441379  2.750
Sun    21.410000  3.150

In [35]:
data.groupby("day")[["total_bill","tip"]].agg({
    "total_bill" : ["mean" , "median"] ,
    "tip" : ["median" , "sum"]
})

     total_bill           tip
           mean median median     sum
day
Thur  17.682742  16.20  2.305  171.83
Fri   17.151579  15.38  3.000   51.96
Sat   20.441379  18.24  2.750  260.40
Sun   21.410000  19.63  3.150  247.39

# pivot table

In [38]:
data

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [36]:
data.pivot_table(values = "total_bill" , index = "sex")

        total_bill
sex
Male     20.744076
Female   18.056897

In [37]:
data.pivot_table(values = "total_bill" , index = "sex" , aggfunc="sum")

        total_bill
sex
Male       3256.82
Female     1570.95

In [39]:
data.pivot_table(values = "size" , columns = "day" , aggfunc = "sum")

day   Thur  Fri  Sat  Sun
size   152   40  219  216

In [48]:
df = sns.load_dataset("flights")
df

     year month  passengers
0    1949   Jan         112
1    1949   Feb         118
2    1949   Mar         132
3    1949   Apr         129
4    1949   May         121
..    ...   ...         ...
139  1960   Aug         606
140  1960   Sep         508
141  1960   Oct         461
142  1960   Nov         390
143  1960   Dec         432

[144 rows x 3 columns]

In [49]:
df.pivot_table(values = "passengers" , columns = "year" , aggfunc="sum")

year,1949,1950,1951,1952,1953,1954,1955,1956,1957,1958,1959,1960
passengers,1520,1676,2042,2364,2700,2867,3408,3939,4421,4572,5140,5714

In [47]:
df.pivot_table(values = "passengers" , columns = "year" , aggfunc="sum" , margins = True)

year,1949,All,1950,All,1951,All,1952,All,1953,All,...,1956,All,1957,All,1958,All,1959,All,1960,All
passengers,1520,1520,1676,1676,2042,2042,2364,2364,2700,2700,...,3939,3939,4421,4421,4572,4572,5140,5140,5714,5714

In [50]:
df.pivot_table(values="passengers" , columns = "month" , index = "year" , aggfunc = "sum")

month  Jan  Feb  Mar  Apr  May  Jun  Jul  Aug  Sep  Oct  Nov  Dec
year
1949   112  118  132  129  121  135  148  148  136  119  104  118
1950   115  126  141  135  125  149  170  170  158  133  114  140
1951   145  150  178  163  172  178  199  199  184  162  146  166
1952   171  180  193  181  183  218  230  242  209  191  172  194
1953   196  196  236  235  229  243  264  272  237  211  180  201
1954   204  188  235  227  234  264  302  293  259  229  203  229
1955   242  233  267  269  270  315  364  347  312  274  237  278
1956   284  277  317  313  318  374  413  405  355  306  271  306
1957   315  301  356  348  355  422  465  467  404  347  305  336
1958   340  318  362  348  363  435  491  505  404  359  310  337
1959   360  342  406  396  420  472  548  559  463  407  362  405
1960   417  391  419  461  472  535  622  606  508  461  390  432

In [51]:
df.pivot_table(values="passengers" , columns = "month" , index = "year" , aggfunc = "sum" , margins = "True")

month,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec,All
year,,,,,,,,,,,,,
1949,112,118,132,129,121,135,148,148,136,119,104,118,1520
1950,115,126,141,135,125,149,170,170,158,133,114,140,1676
1951,145,150,178,163,172,178,199,199,184,162,146,166,2042
1952,171,180,193,181,183,218,230,242,209,191,172,194,2364
1953,196,196,236,235,229,243,264,272,237,211,180,201,2700
1954,204,188,235,227,234,264,302,293,259,229,203,229,2867
1955,242,233,267,269,270,315,364,347,312,274,237,278,3408
1956,284,277,317,313,318,374,413,405,355,306,271,306,3939
1957,315,301,356,348,355,422,465,467,404,347,305,336,4421
1958,340,318,362,348,363,435,491,505,404,359,310,337,4572
1959,360,342,406,396,420,472,548,559,463,407,362,405,5140
1960,417,391,419,461,472,535,622,606,508,461,390,432,5714
All,2901,2820,3242,3205,3262,3740,4216,4213,3629,3199,2794,3142,40363